version: '3.8'
services:
  backend:
    build: .
    container_name: webseccheck-backend
    restart: unless-stopped
    ports:
      - '3000:7860'
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - ADMIN_API_KEY=H1HEi75wXtHfFUV-s4x-rpJLaSSSSM5hmJTY4WzQq5I
      - MP_ACCESS_TOKEN=APP_USR-4055976622260713-022812-7f13d034520ad1960b32ba733712f943-5340422
